//
//  DetailBuildPlanView.swift
//  DIYGenieApp
//
//  Displays a full step-by-step DIY plan generated by AI.
//

import SwiftUI

struct DetailBuildPlanView: View {
    let project: Project

    private var plan: PlanResponse? { project.planJson }
    private var previewURL: URL? {
        if let urlString = project.previewUrl, let url = URL(string: urlString) {
            return url
        }
        return project.photoUrl.flatMap(URL.init(string:))
    }

    @State private var showingShareSheet = false
    @State private var shareItems: [Any] = []
    
    var body: some View {
        ZStack {
            DS.Colors.background
                .ignoresSafeArea()
            
            ScrollView {
                VStack(alignment: .leading, spacing: 24) {
                    if let previewUrl = previewURL {
                        AsyncImage(url: previewUrl) { phase in
                            switch phase {
                            case .success(let image):
                                image
                                    .resizable()
                                    .scaledToFill()
                            case .failure:
                                placeholderImage
                            case .empty:
                                ProgressView()
                                    .progressViewStyle(CircularProgressViewStyle(tint: .white))
                            @unknown default:
                                placeholderImage
                            }
                        }
                        .frame(height: 200)
                        .clipped()
                        .cornerRadius(16)
                        .overlay(
                            RoundedRectangle(cornerRadius: 16)
                                .stroke(DS.Colors.cardBorder, lineWidth: 1)
                        )
                    }

                    if let plan {
                        if let summary = plan.summary, !summary.isEmpty {
                            sectionCard {
                                sectionHeader("Summary")
                                Text(summary)
                                    .font(.body)
                                    .foregroundColor(DS.Colors.textPrimary.opacity(0.85))
                                    .fixedSize(horizontal: false, vertical: true)
                            }
                        }

                        if let notes = plan.notes, !notes.isEmpty {
                            sectionCard {
                                sectionHeader("Before You Begin")
                                Text(notes)
                                    .font(.body)
                                    .foregroundColor(DS.Colors.textPrimary.opacity(0.85))
                                    .fixedSize(horizontal: false, vertical: true)
                            }
                        }

                        if !plan.steps.isEmpty {
                            sectionCard {
                                sectionHeader("Step-by-Step Instructions")
                                VStack(alignment: .leading, spacing: 16) {
                                    ForEach(Array(plan.steps.enumerated()), id: \.element.id) { index, step in
                                        stepCard(step: step, number: index + 1)
                                        if index < plan.steps.count - 1 {
                                            Divider()
                                                .background(DS.Colors.cardBorder)
                                        }
                                    }
                                }
                            }
                        }

                        if !plan.tools.isEmpty {
                            sectionCard {
                                sectionHeader("Required Tools")
                                VStack(alignment: .leading, spacing: 12) {
                                    ForEach(plan.tools) { tool in
                                        Text(tool.name)
                                            .font(.body)
                                            .foregroundColor(DS.Colors.textPrimary)
                                        if tool.id != plan.tools.last?.id {
                                            Divider()
                                                .background(DS.Colors.cardBorder)
                                        }
                                    }
                                }
                            }
                        }

                        if !plan.materials.isEmpty {
                            sectionCard {
                                sectionHeader("Materials")
                                VStack(alignment: .leading, spacing: 12) {
                                    ForEach(plan.materials) { material in
                                        VStack(alignment: .leading, spacing: 4) {
                                            Text(material.name)
                                                .font(.body)
                                                .foregroundColor(DS.Colors.textPrimary)
                                            if let quantity = material.quantity, !quantity.isEmpty {
                                                Text(quantity)
                                                    .font(.footnote)
                                                    .foregroundColor(DS.Colors.textSecondary)
                                            }
                                            if let notes = material.notes, !notes.isEmpty {
                                                Text(notes)
                                                    .font(.footnote)
                                                    .foregroundColor(DS.Colors.textSecondary)
                                            }
                                        }
                                        if material.id != plan.materials.last?.id {
                                            Divider()
                                                .background(DS.Colors.cardBorder)
                                        }
                                    }
                                }
                            }
                        }

                        if let costBreakdown = plan.costBreakdown, !costBreakdown.isEmpty {
                            sectionCard {
                                sectionHeader("Cost Estimate")
                                VStack(alignment: .leading, spacing: 10) {
                                    ForEach(costBreakdown) { item in
                                        VStack(alignment: .leading, spacing: 4) {
                                            Text(item.category)
                                                .font(.callout.weight(.semibold))
                                                .foregroundColor(DS.Colors.textPrimary)
                                            Text(item.amount)
                                                .font(.body)
                                                .foregroundColor(DS.Colors.textPrimary)
                                            if let notes = item.notes, !notes.isEmpty {
                                                Text(notes)
                                                    .font(.footnote)
                                                    .foregroundColor(DS.Colors.textSecondary)
                                            }
                                        }
                                        if item.id != costBreakdown.last?.id {
                                            Divider()
                                                .background(DS.Colors.cardBorder)
                                        }
                                    }
                                }
                            }
                        }
                    } else {
                        sectionCard {
                            sectionHeader("Plan")
                            Text("Your plan is still loading. Try refreshing this project in a moment.")
                                .font(.body)
                                .foregroundColor(DS.Colors.textPrimary.opacity(0.75))
                                .fixedSize(horizontal: false, vertical: true)
                        }
                    }

                    shareButton
                }
                .padding(.horizontal, 20)
                .padding(.top, 20)
                .padding(.bottom, 40)
            }
        }
        .preferredColorScheme(.dark)
        .sheet(isPresented: $showingShareSheet) {
            ShareSheet(activityItems: shareItems)
        }
    }
    
    // MARK: - Components
    
    private var placeholderImage: some View {
        ZStack {
            RoundedRectangle(cornerRadius: 16)
                .fill(DS.Colors.cardOverlay)
            Image(systemName: "photo.on.rectangle")
                .font(.system(size: 36, weight: .semibold))
                .foregroundColor(DS.Colors.textSecondary)
        }
    }
    
    private func sectionCard<Content: View>(@ViewBuilder content: () -> Content) -> some View {
        VStack(alignment: .leading, spacing: 12, content: content)
            .padding(18)
            .frame(maxWidth: .infinity, alignment: .leading)
            .background(DS.Styles.card())
    }
    
    private func sectionHeader(_ title: String) -> some View {
        Text(title)
            .font(.headline.weight(.semibold))
            .foregroundColor(DS.Colors.textPrimary)
    }
    
    private func stepCard(step: PlanStep, number: Int) -> some View {
        VStack(alignment: .leading, spacing: 8) {
            HStack {
                Text("Step \(number)")
                    .font(.headline.weight(.bold))
                    .foregroundColor(DS.Colors.textPrimary)
                    .padding(.horizontal, 12)
                    .padding(.vertical, 6)
                    .background(DS.Colors.lavenderAccent.opacity(0.2))
                    .cornerRadius(8)

                Spacer()

                if let duration = step.estimatedTime, !duration.isEmpty {
                    Text(duration)
                        .font(.footnote.weight(.semibold))
                        .foregroundColor(DS.Colors.textSecondary)
                }
            }
            
            Text(step.title)
                .font(.title3.weight(.semibold))
                .foregroundColor(DS.Colors.textPrimary)
            
            if let details = step.details, !details.isEmpty {
                Text(details)
                    .font(.body)
                    .foregroundColor(DS.Colors.textPrimary.opacity(0.85))
            }
        }
    }

    private var shareButton: some View {
        Button(action: sharePlan) {
            Text("Share Plan")
                .font(.headline.weight(.semibold))
                .foregroundColor(.white)
                .frame(maxWidth: .infinity)
                .padding(.vertical, 14)
                .background(DS.Styles.primaryButton())
                .cornerRadius(14)
        }
    }
    
    private func sharePlan() {
        var items: [Any] = []
        if let summary = plan?.summary {
            items.append(summary)
        } else {
            items.append("DIY build plan")
        }
        shareItems = items
        showingShareSheet = true
    }
}

