//
//  DetailBuildPlanView.swift
//  DIYGenieApp
//
//  Displays a full step-by-step DIY plan generated by AI.
//

import SwiftUI

struct DetailBuildPlanView: View {
    let projectId: UUID
    let plan: PlanV1
    
    @State private var showingShareSheet = false
    @State private var shareItems: [Any] = []
    
    var body: some View {
        ZStack {
            DS.Colors.background
                .ignoresSafeArea()
            
            ScrollView {
                VStack(alignment: .leading, spacing: 24) {
                    // Preview image header
                    if let previewUrl = plan.previewUrl {
                        AsyncImage(url: previewUrl) { phase in
                            switch phase {
                            case .success(let image):
                                image
                                    .resizable()
                                    .scaledToFill()
                            case .failure:
                                placeholderImage
                            case .empty:
                                ProgressView()
                                    .progressViewStyle(CircularProgressViewStyle(tint: .white))
                            @unknown default:
                                placeholderImage
                            }
                        }
                        .frame(height: 200)
                        .clipped()
                        .cornerRadius(16)
                        .overlay(
                            RoundedRectangle(cornerRadius: 16)
                                .stroke(DS.Colors.cardBorder, lineWidth: 1)
                        )
                    }
                    
                    // Summary section
                    if let summary = plan.summary, !summary.isEmpty {
                        sectionCard {
                            sectionHeader("Summary")
                            Text(summary)
                                .font(.body)
                                .foregroundColor(DS.Colors.textPrimary.opacity(0.85))
                                .fixedSize(horizontal: false, vertical: true)
                        }
                    }
                    
                    // Before You Begin
                    if let overview = plan.overview, !overview.isEmpty {
                        sectionCard {
                            sectionHeader("Before You Begin")
                            Text(overview)
                                .font(.body)
                                .foregroundColor(DS.Colors.textPrimary.opacity(0.85))
                                .fixedSize(horizontal: false, vertical: true)
                        }
                    }
                    
                    // Steps section
                    if !plan.steps.isEmpty {
                        sectionCard {
                            sectionHeader("Step-by-Step Instructions")
                            VStack(alignment: .leading, spacing: 16) {
                                ForEach(Array(plan.steps.enumerated()), id: \.element.id) { index, step in
                                    stepCard(step: step, number: index + 1)
                                    if index < plan.steps.count - 1 {
                                        Divider()
                                            .background(DS.Colors.cardBorder)
                                    }
                                }
                            }
                        }
                    }
                    
                    // Tools section
                    if !plan.tools.isEmpty {
                        sectionCard {
                            sectionHeader("Required Tools")
                            VStack(alignment: .leading, spacing: 12) {
                                ForEach(plan.tools) { tool in
                                    planItemRow(name: tool.name, quantity: tool.quantity, unit: tool.unit)
                                    if tool.id != plan.tools.last?.id {
                                        Divider()
                                            .background(DS.Colors.cardBorder)
                                    }
                                }
                            }
                        }
                    }
                    
                    // Materials section
                    if !plan.materials.isEmpty {
                        sectionCard {
                            sectionHeader("Materials")
                            VStack(alignment: .leading, spacing: 12) {
                                ForEach(plan.materials) { material in
                                    planItemRow(name: material.name, quantity: material.quantity, unit: material.unit)
                                    if material.id != plan.materials.last?.id {
                                        Divider()
                                            .background(DS.Colors.cardBorder)
                                    }
                                }
                            }
                        }
                    }
                    
                    // Cut List section
                    if !plan.cuts.isEmpty {
                        sectionCard {
                            sectionHeader("Cut List")
                            VStack(alignment: .leading, spacing: 12) {
                                ForEach(plan.cuts) { cut in
                                    Text(cut.description)
                                        .font(.body)
                                        .foregroundColor(DS.Colors.textPrimary)
                                    if cut.id != plan.cuts.last?.id {
                                        Divider()
                                            .background(DS.Colors.cardBorder)
                                    }
                                }
                            }
                        }
                    }
                    
                    // Cost Estimate section
                    if let cost = plan.cost {
                        sectionCard {
                            sectionHeader("Cost Estimate")
                            VStack(alignment: .leading, spacing: 10) {
                                if let materialsSubtotal = cost.materialsSubtotal {
                                    costRow(title: "Materials", amount: materialsSubtotal)
                                }
                                if let toolsSubtotal = cost.toolsSubtotal {
                                    costRow(title: "Tools", amount: toolsSubtotal)
                                }
                                if let contingencyPercent = cost.contingencyPercent {
                                    if let materialsSubtotal = cost.materialsSubtotal {
                                        let contingency = materialsSubtotal * (contingencyPercent / 100.0)
                                        costRow(title: "Contingency (\(Int(contingencyPercent))%)", amount: contingency)
                                    }
                                }
                                if let total = cost.total {
                                    Divider()
                                        .background(DS.Colors.cardBorder)
                                    costRow(title: "Total", amount: total, isTotal: true)
                                }
                            }
                        }
                    }
                    
                    // Share button
                    shareButton
                }
                .padding(.horizontal, 20)
                .padding(.top, 20)
                .padding(.bottom, 40)
            }
        }
        .preferredColorScheme(.dark)
        .sheet(isPresented: $showingShareSheet) {
            ShareSheet(activityItems: shareItems)
        }
    }
    
    // MARK: - Components
    
    private var placeholderImage: some View {
        ZStack {
            RoundedRectangle(cornerRadius: 16)
                .fill(DS.Colors.cardOverlay)
            Image(systemName: "photo.on.rectangle")
                .font(.system(size: 36, weight: .semibold))
                .foregroundColor(DS.Colors.textSecondary)
        }
    }
    
    private func sectionCard<Content: View>(@ViewBuilder content: () -> Content) -> some View {
        VStack(alignment: .leading, spacing: 12, content: content)
            .padding(18)
            .frame(maxWidth: .infinity, alignment: .leading)
            .background(DS.Styles.card())
    }
    
    private func sectionHeader(_ title: String) -> some View {
        Text(title)
            .font(.headline.weight(.semibold))
            .foregroundColor(DS.Colors.textPrimary)
    }
    
    private func stepCard(step: Step, number: Int) -> some View {
        VStack(alignment: .leading, spacing: 8) {
            HStack {
                Text("Step \(number)")
                    .font(.headline.weight(.bold))
                    .foregroundColor(DS.Colors.textPrimary)
                    .padding(.horizontal, 12)
                    .padding(.vertical, 6)
                    .background(DS.Colors.lavenderAccent.opacity(0.2))
                    .cornerRadius(8)
                
                Spacer()
                
                if let duration = step.durationMinutes {
                    Text("\(duration) min")
                        .font(.footnote.weight(.semibold))
                        .foregroundColor(DS.Colors.textSecondary)
                }
            }
            
            Text(step.title)
                .font(.title3.weight(.semibold))
                .foregroundColor(DS.Colors.textPrimary)
            
            if let details = step.details, !details.isEmpty {
                Text(details)
                    .font(.body)
                    .foregroundColor(DS.Colors.textPrimary.opacity(0.85))
            }
        }
    }
    
    private func planItemRow(name: String, quantity: Double?, unit: String?) -> some View {
        VStack(alignment: .leading, spacing: 4) {
            Text(name)
                .font(.headline)
                .foregroundColor(DS.Colors.textPrimary)
            
            if let quantity = quantity, let unit = unit {
                Text("\(formatQuantity(quantity)) \(unit)")
                    .font(.footnote)
                    .foregroundColor(DS.Colors.textSecondary)
            } else if let quantity = quantity {
                Text(formatQuantity(quantity))
                    .font(.footnote)
                    .foregroundColor(DS.Colors.textSecondary)
            } else if let unit = unit {
                Text(unit)
                    .font(.footnote)
                    .foregroundColor(DS.Colors.textSecondary)
            }
        }
    }
    
    private func costRow(title: String, amount: Double, isTotal: Bool = false) -> some View {
        HStack {
            Text(title)
                .font(isTotal ? .headline : .body)
                .foregroundColor(DS.Colors.textPrimary)
            Spacer()
            Text(formatCurrency(amount))
                .font(isTotal ? .headline.weight(.bold) : .body.weight(.semibold))
                .foregroundColor(DS.Colors.textPrimary)
        }
    }
    
    private var shareButton: some View {
        Button(action: sharePlan) {
            Text("Share Plan")
                .font(.headline.weight(.semibold))
                .foregroundColor(.white)
                .frame(maxWidth: .infinity)
                .padding(.vertical, 14)
                .background(DS.Styles.primaryButton())
                .cornerRadius(14)
        }
    }
    
    // MARK: - Helpers
    
    private func formatQuantity(_ quantity: Double) -> String {
        if quantity.truncatingRemainder(dividingBy: 1) == 0 {
            return String(Int(quantity))
        } else {
            return String(format: "%.2f", quantity)
        }
    }
    
    private func formatCurrency(_ amount: Double) -> String {
        let formatter = NumberFormatter()
        formatter.numberStyle = .currency
        formatter.maximumFractionDigits = 2
        return formatter.string(from: NSNumber(value: amount)) ?? "$\(String(format: "%.2f", amount))"
    }
    
    private func sharePlan() {
        var items: [Any] = []
        if let summary = plan.summary {
            items.append(summary)
        } else {
            items.append("DIY build plan")
        }
        shareItems = items
        showingShareSheet = true
    }
}

