//
//  DetailedBuildPlanView.swift
//  DIYGenieApp
//  Displays a full step-by-step DIY plan generated by AI.
//

import SwiftUI

struct DetailedBuildPlanView: View {
    let plan: PlanResponse?
    let completedSteps: [Int]

    @State private var showingShareSheet = false
    @State private var shareItems: [Any] = []

    private let cardBackground = Color.white.opacity(0.06)

    init(plan: PlanResponse?, completedSteps: [Int] = []) {
        self.plan = plan
        self.completedSteps = completedSteps
    }

    var body: some View {
        ZStack {
            LinearGradient(
                gradient: Gradient(colors: [Color("BGStart"), Color("BGEnd")]),
                startPoint: .topLeading,
                endPoint: .bottomTrailing
            )
            .ignoresSafeArea()

            if let plan {
                ScrollView {
                    VStack(alignment: .leading, spacing: 24) {
                        headerSection(for: plan)
                        summarySection(for: plan)
                        recommendedToolsSection(for: plan.tools)
                        shoppingListSection(for: plan.materials)
                        if shouldShowCutList(for: plan.materials) {
                            cutListSection(for: plan.materials)
                        }
                        stepsSection(for: plan)
                        notesSection(notes: plan.notes)
                        savePlanButton
                    }
                    .padding(.horizontal, 20)
                    .padding(.top, 20)
                    .padding(.bottom, 40)
                }
            } else {
                VStack(spacing: 12) {
                    ProgressView()
                        .progressViewStyle(CircularProgressViewStyle(tint: .white))
                    Text("Loading plan...")
                        .foregroundColor(.white.opacity(0.85))
                        .font(.system(size: 16))
                }
            }
        }
        .preferredColorScheme(.dark)
    }

    // MARK: - Sections

    private func headerSection(for plan: PlanResponse) -> some View {
        VStack(alignment: .leading, spacing: 12) {
            HStack(alignment: .center, spacing: 12) {
                Image(systemName: "doc.text")
                    .foregroundColor(.white)
                    .font(.title3)
                    .padding(10)
                    .background(Color.white.opacity(0.12))
                    .clipShape(RoundedRectangle(cornerRadius: 10))

                VStack(alignment: .leading, spacing: 4) {
                    Text("DIY Build Plan")
                        .font(.system(size: 28, weight: .bold))
                        .foregroundColor(.white)
                    if let duration = timelineValue(from: plan.estimatedDuration) {
                        Text(duration)
                            .font(.subheadline)
                            .foregroundColor(.white.opacity(0.8))
                    }
                }
                Spacer()
            }
        }
    }

    @ViewBuilder
    private func summarySection(for plan: PlanResponse) -> some View {
        VStack(alignment: .leading, spacing: 16) {
            if let overview = plan.summary, !overview.isEmpty {
                Text(overview)
                    .font(.subheadline)
                    .foregroundColor(.white.opacity(0.85))
            }

            VStack(alignment: .leading, spacing: 10) {
                if let cost = plan.estimatedCost, !cost.isEmpty {
                    infoRow(title: "Estimated cost", value: cost)
                }
                if let duration = timelineValue(from: plan.estimatedDuration) {
                    infoRow(title: "Timeline", value: duration)
                }
                if let skill = plan.skillLevel, !skill.isEmpty {
                    infoRow(title: "Skill level", value: skill.capitalized)
                }
            }
        }
        .padding(18)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(cardBackground)
        .cornerRadius(16)
    }

    private func infoRow(title: String, value: String) -> some View {
        HStack {
            Text(title)
                .font(.subheadline)
                .foregroundColor(.white.opacity(0.7))
            Spacer()
            Text(value)
                .font(.subheadline.weight(.semibold))
                .foregroundColor(.white)
        }
    }

    private func recommendedToolsSection(for tools: [PlanTool]) -> some View {
        planListSection(title: "Recommended Tools", hasContent: !tools.isEmpty) {
            VStack(alignment: .leading, spacing: 12) {
                ForEach(Array(tools.enumerated()), id: \.offset) { index, tool in
                    VStack(alignment: .leading, spacing: 4) {
                        Text(tool.name)
                            .font(.headline)
                            .foregroundColor(.white)
                        if let notes = tool.notes, !notes.isEmpty {
                            Text(notes)
                                .font(.footnote)
                                .foregroundColor(.white.opacity(0.7))
                        }
                    }
                    if index < tools.count - 1 {
                        Divider().background(Color.white.opacity(0.12))
                    }
                }
            }
        } emptyContent: {
            planEmptyState("No tools required yet.")
        }
    }

    private func shoppingListSection(for materials: [PlanMaterial]) -> some View {
        planListSection(title: "Shopping List", hasContent: !materials.isEmpty) {
            VStack(alignment: .leading, spacing: 12) {
                ForEach(Array(materials.enumerated()), id: \.offset) { index, material in
                    VStack(alignment: .leading, spacing: 4) {
                        Text(material.name)
                            .font(.headline)
                            .foregroundColor(.white)
                        if let quantity = material.quantity, !quantity.isEmpty {
                            Text(quantity)
                                .font(.footnote)
                                .foregroundColor(.white.opacity(0.75))
                        }
                        if let notes = material.notes, !notes.isEmpty {
                            Text(notes)
                                .font(.footnote)
                                .foregroundColor(.white.opacity(0.65))
                        }
                    }
                    if index < materials.count - 1 {
                        Divider().background(Color.white.opacity(0.12))
                    }
                }
            }
        } emptyContent: {
            planEmptyState("No shopping items listed yet.")
        }
    }

    private func cutListSection(for materials: [PlanMaterial]) -> some View {
        planListSection(title: "Cut List", hasContent: !materials.isEmpty) {
            LazyVStack(spacing: 12) {
                HStack {
                    Text("Board")
                        .font(.footnote.weight(.semibold))
                        .foregroundColor(.white.opacity(0.8))
                    Spacer()
                    Text("Qty")
                        .font(.footnote.weight(.semibold))
                        .foregroundColor(.white.opacity(0.8))
                        .frame(width: 50, alignment: .trailing)
                    Text("Length")
                        .font(.footnote.weight(.semibold))
                        .foregroundColor(.white.opacity(0.8))
                        .frame(width: 90, alignment: .trailing)
                }
                Divider().background(Color.white.opacity(0.2))

                ForEach(Array(materials.enumerated()), id: \.offset) { index, material in
                    HStack(alignment: .top) {
                        Text(material.name)
                            .foregroundColor(.white)
                        Spacer()
                        Text(material.quantity ?? "—")
                            .foregroundColor(.white.opacity(0.85))
                            .frame(width: 50, alignment: .trailing)
                        Text(material.notes ?? "—")
                            .foregroundColor(.white.opacity(0.85))
                            .frame(width: 90, alignment: .trailing)
                    }
                    if index < materials.count - 1 {
                        Divider().background(Color.white.opacity(0.1))
                    }
                }
            }
        } emptyContent: {
            planEmptyState("Add board dimensions to generate a cut list.")
        }
    }

    @ViewBuilder
    private func stepsSection(for plan: PlanResponse) -> some View {
        let orderedPairs = plan.steps.orderedWithOriginalIndices()
        planListSection(title: "Step-by-Step Instructions", hasContent: !orderedPairs.isEmpty) {
            LazyVStack(alignment: .leading, spacing: 16) {
                ForEach(Array(orderedPairs.enumerated()), id: \.offset) { entry in
                    let displayIndex = entry.offset + 1
                    let pair = entry.element
                    PlanStepView(
                        number: displayIndex,
                        title: pair.step.title,
                        description: pair.step.details,
                        imageName: nil,
                        estimatedTime: pair.step.estimatedTime,
                        isComplete: Set(completedSteps).contains(pair.originalIndex)
                    )
                }
            }
        } emptyContent: {
            planEmptyState("No steps yet.")
        }
    }

    private func notesSection(notes: String?) -> some View {
        planListSection(title: "Notes", hasContent: notes?.isEmpty == false) {
            Text(notes ?? "")
                .font(.body)
                .foregroundColor(.white.opacity(0.85))
                .frame(maxWidth: .infinity, alignment: .leading)
        } emptyContent: {
            planEmptyState("No notes added yet.")
        }
    }

    // MARK: - Helpers

    private func timelineValue(from estimatedDuration: String?) -> String? {
        guard let duration = estimatedDuration?.trimmingCharacters(in: .whitespacesAndNewlines), !duration.isEmpty else {
            return nil
        }

        let hasLetters = duration.rangeOfCharacter(in: .letters) != nil
        let hasDigits = duration.rangeOfCharacter(in: .decimalDigits) != nil

        if hasDigits && !hasLetters {
            return "\(duration) min"
        }

        return duration
    }

    private func shouldShowCutList(for materials: [PlanMaterial]) -> Bool {
        materials.contains { material in
            [material.quantity, material.notes].contains { value in
                guard let value, !value.isEmpty else { return false }
                return value.rangeOfCharacter(in: .decimalDigits) != nil
            }
        }
    }

    private func planEmptyState(_ message: String) -> some View {
        Text(message)
            .font(.subheadline)
            .foregroundColor(.white.opacity(0.65))
            .frame(maxWidth: .infinity, alignment: .leading)
            .padding(16)
            .background(cardBackground)
            .cornerRadius(16)
    }

    @ViewBuilder
    private func planListSection<Content: View, Empty: View>(
        title: String,
        hasContent: Bool,
        @ViewBuilder content: () -> Content,
        @ViewBuilder emptyContent: () -> Empty
    ) -> some View {
        VStack(alignment: .leading, spacing: 12) {
            Text(title)
                .font(.headline.weight(.semibold))
                .foregroundColor(.white)

            if hasContent {
                VStack(alignment: .leading, spacing: 0, content: content)
                    .padding(16)
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .background(cardBackground)
                    .cornerRadius(16)
            } else {
                emptyContent()
            }
        }
    }

    private var savePlanButton: some View {
        Button(action: sharePlan) {
            Text("Save Plan")
                .font(.headline.weight(.semibold))
                .foregroundColor(.white)
                .frame(maxWidth: .infinity)
                .padding(.vertical, 16)
                .background(Color.white.opacity(0.14))
                .cornerRadius(16)
        }
        .sheet(isPresented: $showingShareSheet) {
            ShareSheet(activityItems: shareItems)
        }
    }

    private func sharePlan() {
        if let summary = plan?.summary {
            shareItems = [summary]
        } else {
            shareItems = ["DIY build plan"]
        }
        showingShareSheet = true
    }
}

private struct PlanStepView: View {
    let number: Int
    let title: String
    let description: String?
    let imageName: String?
    let estimatedTime: String?
    let isComplete: Bool

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            HStack(alignment: .center, spacing: 12) {
                Text("Step \(number)")
                    .font(.headline.weight(.bold))
                    .padding(.horizontal, 12)
                    .padding(.vertical, 8)
                    .background(Color.white.opacity(0.18))
                    .clipShape(RoundedRectangle(cornerRadius: 10))
                Spacer()
                Image(systemName: isComplete ? "checkmark.circle.fill" : "circle")
                    .foregroundColor(isComplete ? Color.green : Color.white.opacity(0.7))
            }

            Text(title)
                .font(.title3.weight(.semibold))
                .foregroundColor(.white)

            if let description, !description.isEmpty {
                Text(description)
                    .font(.body)
                    .foregroundColor(.white.opacity(0.9))
            }

            if let estimatedTime, !estimatedTime.isEmpty {
                Text("Estimated time: \(estimatedTime)")
                    .font(.footnote.weight(.semibold))
                    .foregroundColor(.white.opacity(0.85))
            }

            if let imageName {
                Image(imageName)
                    .resizable()
                    .scaledToFit()
                    .frame(maxWidth: .infinity)
                    .cornerRadius(10)
            }
        }
        .padding(14)
        .background(Color.white.opacity(0.06))
        .cornerRadius(16)
    }
}
