//
//  DetailedBuildPlanView.swift
//  DIYGenieApp
//  Displays a full step-by-step DIY plan generated by AI.
//

import SwiftUI

struct DetailedBuildPlanView: View {
    let plan: PlanResponse?
    let completedSteps: [Int]

    init(plan: PlanResponse?, completedSteps: [Int] = []) {
        self.plan = plan
        self.completedSteps = completedSteps
    }

    var body: some View {
        ZStack {
            LinearGradient(
                gradient: Gradient(colors: [Color("BGStart"), Color("BGEnd")]),
                startPoint: .topLeading,
                endPoint: .bottomTrailing
            )
            .ignoresSafeArea()

            if let plan {
                ScrollView {
                    VStack(alignment: .leading, spacing: 24) {
                        headerSection
                        summarySection(for: plan)
                        materialsSection(for: plan.materials)
                        toolsSection(for: plan.tools)
                        if let breakdown = plan.costBreakdown {
                            costBreakdownSection(for: breakdown)
                        }
                        stepsSection(for: plan)
                        if let notes = plan.notes, !notes.isEmpty {
                            notesSection(notes)
                        }
                    }
                    .padding(.horizontal, 20)
                    .padding(.top, 20)
                    .padding(.bottom, 40)
                }
            } else {
                VStack(spacing: 12) {
                    ProgressView()
                        .progressViewStyle(CircularProgressViewStyle(tint: .white))
                    Text("Loading plan...")
                        .foregroundColor(.white.opacity(0.85))
                        .font(.system(size: 16))
                }
            }
        }
        .preferredColorScheme(.dark)
    }

    private var headerSection: some View {
        HStack {
            Image(systemName: "wrench.and.screwdriver")
                .foregroundColor(.white.opacity(0.9))
                .font(.title2)
            Text("Detailed Build Plan")
                .font(.system(size: 30, weight: .bold))
                .foregroundColor(.white)
            Spacer()
        }
    }

    @ViewBuilder
    private func summarySection(for plan: PlanResponse) -> some View {
        VStack(alignment: .leading, spacing: 16) {
            if let overview = plan.summary, !overview.isEmpty {
                Text(overview)
                    .font(.subheadline)
                    .foregroundColor(.white.opacity(0.75))
            }

            VStack(alignment: .leading, spacing: 10) {
                if let cost = plan.estimatedCost, !cost.isEmpty {
                    infoRow(title: "Estimated cost", value: cost)
                }
                if let duration = plan.estimatedDuration, !duration.isEmpty {
                    infoRow(title: "Duration", value: duration)
                }
                if let skill = plan.skillLevel, !skill.isEmpty {
                    infoRow(title: "Skill level", value: skill.capitalized)
                }
            }
        }
        .padding(18)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(Color.white.opacity(0.08))
        .cornerRadius(18)
    }

    private func infoRow(title: String, value: String) -> some View {
        HStack {
            Text(title)
                .font(.subheadline)
                .foregroundColor(.white.opacity(0.7))
            Spacer()
            Text(value)
                .font(.subheadline.weight(.semibold))
                .foregroundColor(.white)
        }
    }

    @ViewBuilder
    private func materialsSection(for materials: [PlanMaterial]) -> some View {
        planListSection(title: "Materials", hasContent: !materials.isEmpty) {
            ForEach(Array(materials.enumerated()), id: \.offset) { index, material in
                VStack(alignment: .leading, spacing: 4) {
                    Text(material.name)
                        .font(.headline)
                        .foregroundColor(.white)
                    if let quantity = material.quantity, !quantity.isEmpty {
                        Text(quantity)
                            .font(.footnote)
                            .foregroundColor(.white.opacity(0.75))
                    }
                    if let notes = material.notes, !notes.isEmpty {
                        Text(notes)
                            .font(.footnote)
                            .foregroundColor(.white.opacity(0.6))
                    }
                }
                .frame(maxWidth: .infinity, alignment: .leading)
                .padding(.vertical, 6)

                if index < materials.count - 1 {
                    Divider().background(Color.white.opacity(0.12))
                }
            }
        } emptyContent: {
            planEmptyState("No materials listed yet.")
        }
    }

    @ViewBuilder
    private func toolsSection(for tools: [PlanTool]) -> some View {
        planListSection(title: "Tools", hasContent: !tools.isEmpty) {
            ForEach(Array(tools.enumerated()), id: \.offset) { index, tool in
                VStack(alignment: .leading, spacing: 4) {
                    Text(tool.name)
                        .font(.headline)
                        .foregroundColor(.white)
                    if let notes = tool.notes, !notes.isEmpty {
                        Text(notes)
                            .font(.footnote)
                            .foregroundColor(.white.opacity(0.65))
                    }
                }
                .frame(maxWidth: .infinity, alignment: .leading)
                .padding(.vertical, 6)

                if index < tools.count - 1 {
                    Divider().background(Color.white.opacity(0.12))
                }
            }
        } emptyContent: {
            planEmptyState("No tools required yet.")
        }
    }

    @ViewBuilder
    private func costBreakdownSection(for items: [PlanCostItem]) -> some View {
        planListSection(title: "Cost breakdown", hasContent: !items.isEmpty) {
            ForEach(Array(items.enumerated()), id: \.offset) { index, item in
                VStack(alignment: .leading, spacing: 4) {
                    HStack {
                        Text(item.category)
                            .font(.headline)
                            .foregroundColor(.white)
                        Spacer()
                        Text(item.amount)
                            .font(.subheadline.weight(.semibold))
                            .foregroundColor(.white.opacity(0.9))
                    }
                    if let notes = item.notes, !notes.isEmpty {
                        Text(notes)
                            .font(.footnote)
                            .foregroundColor(.white.opacity(0.65))
                    }
                }
                .padding(.vertical, 6)

                if index < items.count - 1 {
                    Divider().background(Color.white.opacity(0.12))
                }
            }
        } emptyContent: {
            planEmptyState("No cost breakdown yet.")
        }
    }

    @ViewBuilder
    private func stepsSection(for plan: PlanResponse) -> some View {
        let orderedPairs = plan.steps.orderedWithOriginalIndices()
        planListSection(title: "Steps", hasContent: !orderedPairs.isEmpty) {
            let completed = Set(completedSteps)
            let progress = Double(completed.count) / Double(max(orderedPairs.count, 1))

            VStack(alignment: .leading, spacing: 8) {
                Text("Progress")
                    .font(.headline.weight(.semibold))
                    .foregroundColor(.white)
                ProgressView(value: progress)
                    .tint(Color.purple)
                Text("\(completed.count) of \(orderedPairs.count) steps complete")
                    .font(.caption)
                    .foregroundColor(.white.opacity(0.7))
            }
            .padding(.bottom, 8)

            ForEach(Array(orderedPairs.enumerated()), id: \.offset) { entry in
                let displayIndex = entry.offset + 1
                let pair = entry.element
                StepCard(
                    number: displayIndex,
                    step: pair.step,
                    isComplete: completed.contains(pair.originalIndex)
                )

                if entry.offset < orderedPairs.count - 1 {
                    Divider().background(Color.white.opacity(0.12))
                }
            }
        } emptyContent: {
            planEmptyState("No steps yet.")
        }
    }

    private func notesSection(_ notes: String) -> some View {
        planListSection(title: "Notes", hasContent: true) {
            Text(notes)
                .font(.body)
                .foregroundColor(.white.opacity(0.85))
                .frame(maxWidth: .infinity, alignment: .leading)
        } emptyContent: {
            EmptyView()
        }
    }

    // MARK: - Helpers

    private func planEmptyState(_ message: String) -> some View {
        Text(message)
            .font(.subheadline)
            .foregroundColor(.white.opacity(0.65))
            .frame(maxWidth: .infinity, alignment: .leading)
            .padding(16)
            .background(Color.white.opacity(0.04))
            .cornerRadius(14)
    }

    @ViewBuilder
    private func planListSection<Content: View, Empty: View>(
        title: String,
        hasContent: Bool,
        @ViewBuilder content: () -> Content,
        @ViewBuilder emptyContent: () -> Empty
    ) -> some View {
        VStack(alignment: .leading, spacing: 12) {
            Text(title)
                .font(.headline.weight(.semibold))
                .foregroundColor(.white)

            if hasContent {
                VStack(alignment: .leading, spacing: 0, content: content)
                    .padding(16)
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .background(Color.white.opacity(0.08))
                    .cornerRadius(16)
            } else {
                emptyContent()
            }
        }
    }
}

private struct StepCard: View {
    let number: Int
    let step: PlanStep
    let isComplete: Bool

    var body: some View {
        HStack(alignment: .top, spacing: 12) {
            Image(systemName: isComplete ? "checkmark.circle.fill" : "circle")
                .foregroundColor(isComplete ? Color.green : Color.white.opacity(0.6))
                .font(.system(size: 18, weight: .semibold))

            VStack(alignment: .leading, spacing: 6) {
                Text("Step \(number)")
                    .font(.subheadline.weight(.semibold))
                    .foregroundColor(.white)
                Text(step.title)
                    .font(.headline)
                    .foregroundColor(.white)
                if let details = step.details, !details.isEmpty {
                    Text(details)
                        .font(.body)
                        .foregroundColor(.white.opacity(0.9))
                }
                if let estimate = step.estimatedTime, !estimate.isEmpty {
                    Text("Estimated time: \(estimate)")
                        .font(.footnote)
                        .foregroundColor(.white.opacity(0.7))
                }
            }
            Spacer(minLength: 0)
        }
    }
}
